#include <stdlib.h>
#include <string.h>
#include <stdio.h>

void n2w(int num) {
  int h = num / 100;
  int t = (num % 100);
  char *words[] = {"zero","one","two","three","four",
                "five","six","seven","eight","nine","ten",
                "eleven","twelve","thirteen","fourteen",
                "fifteen","sixteen","seventeen","eighteen",
                "nineteen" };
  if(h > 0) {
    printf("%s hundred", words[h]);
  }
  if(t > 0) {
     if(h > 0) {
       printf(" and ");
     }
     char *tens[] = {"twenty","thirty","forty","fifty",
                "sixty","seventy","eighty","ninety","hundred"};
     if(t >= 20) {
       printf("%s", tens[(t / 10) - 2]);
       t %= 10;
       if(t > 0) printf(" ");
     }
     if(t > 0) {
       printf("%s", words[t]);
     }
  }
}

int main() {
  char numbuf[15000];
  scanf("%s",numbuf);
  int l = strlen(numbuf);
  char *lions[] = {
      "","thousand","million","billion","trillion",
      "quadrillion","quintillion","sexillion","septillion",
      "octillion","nonillion","decillion","undecillion",
      "duodecillion","tredecillion","quattuordecillion","quindecillion",
      "sexdecillion","septdecillion","octodecillion","novemdecillion",
      "vigintillion","unvigintillion","duovigintillion","trevigintillion",
      "quattuorvigintillion","quinvigintillion","sexvigintillion","septvigintillion",
      "octovigintillion","novemvigintillion","trigintillion","untrigintillion",
      "duotrigintillion","googol","","tretrigintillion",
      "quattuortrigintillion","quintrigintillion","sextrigintillion","septtrigintillion",
      "octotrigintillion","novemtrigintillion","quadragintillion","unquadragintillion",
      "duoquadragintillion","trequadragintillion","quattuorquadragintillion","quinquadragintillion",
      "sexquadragintillion","septquadragintillion","octoquadragintillion","novemquadragintillion",
      "quinquagintillion","unquinquagintillion","duoquinquagintillion","trequinquagintillion",
      "quattuorquinquagintillion","quinquinquagintillion","sexquinquagintillion","septquinquagintillion",
      "octoquinquagintillion","novemquinquagintillion","sexagintillion trigintilliard","unsexagintillion untrigintillion",
      "duosexagintillion untrigintilliard","tresexagintillion duotrigintillion","quattuorsexagintillion","quinsexagintillion",
      "sexsexagintillion","septsexagintillion","octosexagintillion","novemsexagintillion",
      "septuagintillion","unseptuagintillion","duoseptuagintillion","treseptuagintillion",
      "quattuorseptuagintillion","quinseptuagintillion","sexseptuagintillion","septseptuagintillion",
      "octoseptuagintillion","novemseptuagintillion","octogintillion","unoctogintillion",
      "duooctogintillion","treoctogintillion","quattuoroctogintillion","quinoctogintillion",
      "sexoctogintillion","septoctogintillion","octooctogintillion","novemoctogintillion",
      "nonagintillion","unnonagintillion","duononagintillion","trenonagintillion",
      "quattuornonagintillion","quinnonagintillion","sexnonagintillion","septnonagintillion",
      "octononagintillion","novemnonagintillion","centillion","Centummillion or uncentillion",
      "duocentillion","trecentillion","quattuorcentillion","quinquacentillion",
      "sexcentillion","septencentillion","octocentillion","novencentillion",
      "decicentillion","undecicentillion","duodecicentillion","tredecicentillion",
      "quattuordecicentillion","quinquadecicentillion","Centumsedecillion or Sedecicentillion","septendecicentillion",
      "octodecicentillion","novendecicentillion","viginticentillion","Primovigesimocentillion or unviginticentillion",
      "duoviginticentillion","tresviginticentillion","quattuorviginticentillion","quinquaviginticentillion",
      "sesviginticentillion","septemviginticentillion","octoviginticentillion","centumvigintinonillion centumundetrigintillion or novemviginticentillion",
      "Trigintacentillion","Untrigintacentillion","Duotrigintacentillion","Trestrigintacentillion",
      "quattuortrigintacentillion","quinquatrigintacentillion","sestrigintacentillion","septentrigintacentillion",
      "octotrigintacentillion","Noventrigintacentillion or bentaggoogol","quadragintacentillion","unquadragintacentillion",
      "duoquadragintacentillion","tresquadragintacentillion","quattuorquadragintacentillion","quinquaquadragintacentillion",
      "sesquadragintacentillion","septenquadragintacentillion","octoquadragintacentillion","novenquadragintacentillion",
      "quinquagintacentillion","unquinquagintacentillion","duoquinquagintacentillion","tresquinquagintacentillion",
      "quattuorquinquagintacentillion","quinquaquinquagintacentillion","sesquinquagintacentillion","septenquinquagintacentillion",
      "octoquinquagintacentillion","novenquinquagintacentillion","sexagintacentillion","unsexagintacentillion",
      "duosexagintacentillion","tresexagintacentillion","quattuorsexagintacentillion","quinquasexagintacentillion",
      "sesexagintacentillion","septensexagintacentillion","octosexagintacentillion","novensexagintacentillion",
      "septuagintacentillion","unseptuagintacentillion","duoseptuagintacentillion","treseptuagintacentillion",
      "quattuorseptuagintacentillion","quinquaseptuagintacentillion","seseptuagintacentillion","septenseptuagintacentillion",
      "octoseptuagintacentillion","novenseptuagintacentillion","octogintacentillion","unoctogintacentillion",
      "duooctogintacentillion","tresoctogintacentillion","quattuoroctogintacentillion","quinquaoctogintacentillion",
      "sexoctogintacentillion","septemoctogintacentillion","octooctogintacentillion","novemoctogintacentillion",
      "nonagintacentillion","unnonagintacentillion","duononagintacentillion","trenonagintacentillion",
      "quattuornonagintacentillion","quinquanonagintacentillion","senonagintacentillion","septenonagintacentillion",
      "octononagintacentillion","Undeducentillion or Novenonagintacentillion","Ducentillion","unducentillion",
      "duoducentillion","treducentillion","quattuorducentillion","quinquaducentillion",
      "seducentillion","Septenducentillion","octoducentillion","Novenducentillion or tentaggoogol",
      "deciducentillion","undeciducentillion","duodeciducentillion","tredeciducentillion",
      "quattuordeciducentillion","quinquadeciducentillion","sedeciducentillion","septendeciducentillion",
      "octodeciducentillion","novendeciducentillion","Vigintiducentillion eleventyillardplex","unvigintiducentillion",
      "duovigintiducentillion","tresvigintiducentillion","quattuorvigintiducentillion","quinquavigintiducentillion",
      "sesvigintiducentillion","septemvigintiducentillion","octovigintiducentillion","novemvigintiducentillion",
      "trigintaducentillion","untrigintaducentillion","duotrigintaducentillion","trestrigintaducentillion",
      "quattuortrigintaducentillion","quinquatrigintaducentillion","sestrigintaducentillion","septentrigintaducentillion",
      "octotrigintaducentillion","noventrigintaducentillion","quadragintaducentillion","unquadragintaducentillion",
      "duoquadragintaducentillion","tresquadragintaducentillion","quattuorquadragintaducentillion","quinquaquadragintaducentillion",
      "sesquadragintaducentillion","septenquadragintaducentillion","octoquadragintaducentillion","novenquadragintaducentillion",
      "quinquagintaducentillion","unquinquagintaducentillion","duoquinquagintaducentillion","tresquinquagintaducentillion",
      "quattuorquinquagintaducentillion","quinquaquinquagintaducentillion","sesquinquagintaducentillion","septenquinquagintaducentillion",
      "octoquinquagintaducentillion","novenquinquagintaducentillion","sexagintaducentillion","unsexagintaducentillion",
      "duosexagintaducentillion","tresexagintaducentillion","quattuorsexagintaducentillion","quinquasexagintaducentillion",
      "sesexagintaducentillion","septensexagintaducentillion","octosexagintaducentillion","novensexagintaducentillion",
      "septuagintaducentillion","unseptuagintaducentillion","duoseptuagintaducentillion","treseptuagintaducentillion",
      "quattuorseptuagintaducentillion","quinquaseptuagintaducentillion","seseptuagintaducentillion","septenseptuagintaducentillion",
      "octoseptuagintaducentillion","novenseptuagintaducentillion","octogintaducentillion","unoctogintaducentillion",
      "duooctogintaducentillion","tresoctogintaducentillion","quattuoroctogintaducentillion","quinquaoctogintaducentillion",
      "sexoctogintaducentillion","septemoctogintaducentillion","octooctogintaducentillion","novemoctogintaducentillion",
      "nonagintaducentillion","unnonagintaducentillion","duononagintaducentillion","trenonagintaducentillion",
      "quattuornonagintaducentillion","quinquanonagintaducentillion","senonagintaducentillion","septenonagintaducentillion",
      "octononagintaducentillion","Novenonagintaducentillion","Trecentillion","untrecentillion",
      "duotrecentillion","trestrecentillion","quattuortrecentillion","quinquatrecentillion",
      "sestrecentillion","septentrecentillion","octotrecentillion","noventrecentillion",
      "decitrecentillion","undecitrecentillion","duodecitrecentillion","tredecitrecentillion",
      "Trecentiquattuordecillion or quattuordecitrecentillion","quinquadecitrecentillion","sedecitrecentillion","septendecitrecentillion",
      "octodecitrecentillion","novendecitrecentillion","vigintitrecentillion","unvigintitrecentillion",
      "duovigintitrecentillion","tresvigintitrecentillion","quattuorvigintitrecentillion","quinquavigintitrecentillion",
      "sesvigintitrecentillion","septemvigintitrecentillion","octovigintitrecentillion","novemvigintitrecentillion",
      "trigintatrecentillion","untrigintatrecentillion","duotrigintatrecentillion","trestrigintatrecentillion",
      "quattuortrigintatrecentillion","quinquatrigintatrecentillion","sestrigintatrecentillion","septentrigintatrecentillion",
      "octotrigintatrecentillion","noventrigintatrecentillion","quadragintatrecentillion","unquadragintatrecentillion",
      "duoquadragintatrecentillion","tresquadragintatrecentillion","quattuorquadragintatrecentillion","quinquaquadragintatrecentillion",
      "sesquadragintatrecentillion","septenquadragintatrecentillion","octoquadragintatrecentillion","novenquadragintatrecentillion",
      "quinquagintatrecentillion","unquinquagintatrecentillion","duoquinquagintatrecentillion","tresquinquagintatrecentillion",
      "quattuorquinquagintatrecentillion","quinquaquinquagintatrecentillion","sesquinquagintatrecentillion","septenquinquagintatrecentillion",
      "octoquinquagintatrecentillion","novenquinquagintatrecentillion","sexagintatrecentillion","unsexagintatrecentillion",
      "duosexagintatrecentillion","tresexagintatrecentillion","quattuorsexagintatrecentillion","quinquasexagintatrecentillion",
      "sesexagintatrecentillion","septensexagintatrecentillion","octosexagintatrecentillion","novensexagintatrecentillion",
      "septuagintatrecentillion","unseptuagintatrecentillion","duoseptuagintatrecentillion","treseptuagintatrecentillion",
      "quattuorseptuagintatrecentillion","quinquaseptuagintatrecentillion","seseptuagintatrecentillion","septenseptuagintatrecentillion",
      "octoseptuagintatrecentillion","novenseptuagintatrecentillion","octogintatrecentillion","unoctogintatrecentillion",
      "duooctogintatrecentillion","tresoctogintatrecentillion","quattuoroctogintatrecentillion","quinquaoctogintatrecentillion",
      "sexoctogintatrecentillion","septemoctogintatrecentillion","octooctogintatrecentillion","novemoctogintatrecentillion",
      "nonagintatrecentillion","unnonagintatrecentillion","duononagintatrecentillion","trenonagintatrecentillion",
      "quattuornonagintatrecentillion","quinquanonagintatrecentillion","senonagintatrecentillion","septenonagintatrecentillion",
      "octononagintatrecentillion","novenonagintatrecentillion","Quadringentillion","unquadringentillion",
      "duoquadringentillion","tresquadringentillion","quattuorquadringentillion","quinquaquadringentillion",
      "sesquadringentillion","septenquadringentillion","octoquadringentillion","novenquadringentillion",
      "deciquadringentillion","undeciquadringentillion","duodeciquadringentillion","tredeciquadringentillion",
      "quattuordeciquadringentillion","quinquadeciquadringentillion","sedeciquadringentillion","septendeciquadringentillion",
      "octodeciquadringentillion","novendeciquadringentillion","vigintiquadringentillion","unvigintiquadringentillion",
      "duovigintiquadringentillion","tresvigintiquadringentillion","quattuorvigintiquadringentillion","quinquavigintiquadringentillion",
      "sesvigintiquadringentillion","septemvigintiquadringentillion","octovigintiquadringentillion","novemvigintiquadringentillion",
      "trigintaquadringentillion","untrigintaquadringentillion","duotrigintaquadringentillion","trestrigintaquadringentillion",
      "quattuortrigintaquadringentillion","quinquatrigintaquadringentillion","sestrigintaquadringentillion","septentrigintaquadringentillion",
      "octotrigintaquadringentillion","noventrigintaquadringentillion","quadragintaquadringentillion","unquadragintaquadringentillion",
      "duoquadragintaquadringentillion","tresquadragintaquadringentillion","quattuorquadragintaquadringentillion","quinquaquadragintaquadringentillion",
      "sesquadragintaquadringentillion","septenquadragintaquadringentillion","octoquadragintaquadringentillion","novenquadragintaquadringentillion",
      "quinquagintaquadringentillion","unquinquagintaquadringentillion","duoquinquagintaquadringentillion","tresquinquagintaquadringentillion",
      "quattuorquinquagintaquadringentillion","quinquaquinquagintaquadringentillion","sesquinquagintaquadringentillion","septenquinquagintaquadringentillion",
      "octoquinquagintaquadringentillion","novenquinquagintaquadringentillion","sexagintaquadringentillion","unsexagintaquadringentillion",
      "duosexagintaquadringentillion","tresexagintaquadringentillion","quattuorsexagintaquadringentillion","quinquasexagintaquadringentillion",
      "sesexagintaquadringentillion","septensexagintaquadringentillion","octosexagintaquadringentillion","novensexagintaquadringentillion",
      "septuagintaquadringentillion","unseptuagintaquadringentillion","duoseptuagintaquadringentillion","treseptuagintaquadringentillion",
      "quattuorseptuagintaquadringentillion","quinquaseptuagintaquadringentillion","seseptuagintaquadringentillion","septenseptuagintaquadringentillion",
      "octoseptuagintaquadringentillion","novenseptuagintaquadringentillion","octogintaquadringentillion","unoctogintaquadringentillion",
      "duooctogintaquadringentillion","tresoctogintaquadringentillion","quattuoroctogintaquadringentillion","quinquaoctogintaquadringentillion",
      "sexoctogintaquadringentillion","septemoctogintaquadringentillion","octooctogintaquadringentillion","novemoctogintaquadringentillion",
      "nonagintaquadringentillion","unnonagintaquadringentillion","duononagintaquadringentillion","trenonagintaquadringentillion",
      "quattuornonagintaquadringentillion","quinquanonagintaquadringentillion","senonagintaquadringentillion","septenonagintaquadringentillion",
      "octononagintaquadringentillion","novenonagintaquadringentillion","Quingentillion","unquingentillion",
      "duoquingentillion","tresquingentillion","quattuorquingentillion","quinquaquingentillion",
      "sesquingentillion","septenquingentillion","octoquingentillion","novenquingentillion or Megafugafour",
      "deciquingentillion","undeciquingentillion","duodeciquingentillion","tredeciquingentillion",
      "quattuordeciquingentillion","quinquadeciquingentillion","sedeciquingentillion","septendeciquingentillion",
      "octodeciquingentillion","novendeciquingentillion","vigintiquingentillion","unvigintiquingentillion",
      "duovigintiquingentillion","tresvigintiquingentillion","quattuorvigintiquingentillion","quinquavigintiquingentillion",
      "sesvigintiquingentillion","septemvigintiquingentillion","octovigintiquingentillion","novemvigintiquingentillion",
      "trigintaquingentillion","untrigintaquingentillion","duotrigintaquingentillion","trestrigintaquingentillion",
      "quattuortrigintaquingentillion","quinquatrigintaquingentillion","sestrigintaquingentillion","septentrigintaquingentillion",
      "octotrigintaquingentillion","noventrigintaquingentillion","quadragintaquingentillion","unquadragintaquingentillion",
      "duoquadragintaquingentillion","tresquadragintaquingentillion","quattuorquadragintaquingentillion","quinquaquadragintaquingentillion",
      "sesquadragintaquingentillion","septenquadragintaquingentillion","octoquadragintaquingentillion","novenquadragintaquingentillion",
      "quinquagintaquingentillion","Uunquinquagintaquingentillion","duoquinquagintaquingentillion","tresquinquagintaquingentillion",
      "quattuorquinquagintaquingentillion","quinquaquinquagintaquingentillion","sesquinquagintaquingentillion","septenquinquagintaquingentillion",
      "octoquinquagintaquingentillion","novenquinquagintaquingentillion","sexagintaquingentillion","unsexagintaquingentillion",
      "duosexagintaquingentillion","tresexagintaquingentillion","quattuorsexagintaquingentillion","quinquasexagintaquingentillion",
      "sesexagintaquingentillion","septensexagintaquingentillion","octosexagintaquingentillion","novensexagintaquingentillion",
      "septuagintaquingentillion","unseptuagintaquingentillion","duoseptuagintaquingentillion","treseptuagintaquingentillion",
      "quattuorseptuagintaquingentillion","quinquaseptuagintaquingentillion","seseptuagintaquingentillion","septenseptuagintaquingentillion",
      "octoseptuagintaquingentillion","novenseptuagintaquingentillion","octogintaquingentillion","unoctogintaquingentillion",
      "duooctogintaquingentillion","tresoctogintaquingentillion","quattuoroctogintaquingentillion","quinquaoctogintaquingentillion",
      "sexoctogintaquingentillion","septemoctogintaquingentillion","octooctogintaquingentillion","novemoctogintaquingentillion",
      "nonagintaquingentillion","unnonagintaquingentillion","duononagintaquingentillion","trenonagintaquingentillion",
      "quattuornonagintaquingentillion","quinquanonagintaquingentillion","senonagintaquingentillion","septenonagintaquingentillion",
      "octononagintaquingentillion","novenonagintaquingentillion","Sescentillion","unsescentillion",
      "duosescentillion","tresescentillion","quattuorsescentillion","quinquasescentillion",
      "sesescentillion","septensescentillion","octosescentillion","novensescentillion",
      "decisescentillion","undecisescentillion","duodecisescentillion","tredecisescentillion",
      "quattuordecisescentillion","quinquadecisescentillion","sedecisescentillion","septendecisescentillion",
      "octodecisescentillion","novendecisescentillion","vigintisescentillion","unvigintisescentillion",
      "duovigintisescentillion","tresvigintisescentillion","quattuorvigintisescentillion","quinquavigintisescentillion",
      "sesvigintisescentillion","septemvigintisescentillion","octovigintisescentillion","novemvigintisescentillion",
      "trigintasescentillion","untrigintasescentillion","duotrigintasescentillion","trestrigintasescentillion",
      "quattuortrigintasescentillion","quinquatrigintasescentillion","sestrigintasescentillion","septentrigintasescentillion",
      "octotrigintasescentillion","noventrigintasescentillion","quadragintasescentillion","unquadragintasescentillion",
      "duoquadragintasescentillion","tresquadragintasescentillion","quattuorquadragintasescentillion","quinquaquadragintasescentillion",
      "sesquadragintasescentillion","septenquadragintasescentillion","octoquadragintasescentillion","novenquadragintasescentillion",
      "quinquagintasescentillion","unquinquagintasescentillion","duoquinquagintasescentillion","tresquinquagintasescentillion",
      "quattuorquinquagintasescentillion","quinquaquinquagintasescentillion","sesquinquagintasescentillion","septenquinquagintasescentillion",
      "octoquinquagintasescentillion","novenquinquagintasescentillion","sexagintasescentillion","unsexagintasescentillion",
      "duosexagintasescentillion","tresexagintasescentillion","quattuorsexagintasescentillion","quinquasexagintasescentillion",
      "sesexagintasescentillion","septensexagintasescentillion","octosexagintasescentillion","novensexagintasescentillion",
      "septuagintasescentillion","unseptuagintasescentillion","duoseptuagintasescentillion","treseptuagintasescentillion",
      "quattuorseptuagintasescentillion","quinquaseptuagintasescentillion","seseptuagintasescentillion","septenseptuagintasescentillion",
      "octoseptuagintasescentillion","novenseptuagintasescentillion","octogintasescentillion","unoctogintasescentillion",
      "duooctogintasescentillion","tresoctogintasescentillion","quattuoroctogintasescentillion","quinquaoctogintasescentillion",
      "sexoctogintasescentillion","septemoctogintasescentillion","octooctogintasescentillion","novemoctogintasescentillion",
      "nonagintasescentillion","unnonagintasescentillion","duononagintasescentillion","trenonagintasescentillion",
      "quattuornonagintasescentillion","quinquanonagintasescentillion","senonagintasescentillion","septenonagintasescentillion",
      "octononagintasescentillion","novenonagintasescentillion","Septingentillion","unseptingentillion",
      "duoseptingentillion","treseptingentillion","quattuorseptingentillion","quinquaseptingentillion",
      "seseptingentillion","septenseptingentillion","octoseptingentillion","novenseptingentillion",
      "deciseptingentillion","undeciseptingentillion","duodeciseptingentillion","tredeciseptingentillion",
      "quattuordeciseptingentillion","quinquadeciseptingentillion","sedeciseptingentillion","septendeciseptingentillion",
      "octodeciseptingentillion","novendeciseptingentillion","vigintiseptingentillion","unvigintiseptingentillion",
      "duovigintiseptingentillion","tresvigintiseptingentillion","quattuorvigintiseptingentillion","quinquavigintiseptingentillion",
      "sesvigintiseptingentillion","septemvigintiseptingentillion","octovigintiseptingentillion","novemvigintiseptingentillion",
      "trigintaseptingentillion","untrigintaseptingentillion","duotrigintaseptingentillion","trestrigintaseptingentillion",
      "quattuortrigintaseptingentillion","quinquatrigintaseptingentillion","sestrigintaseptingentillion","septentrigintaseptingentillion",
      "octotrigintaseptingentillion","noventrigintaseptingentillion","quadragintaseptingentillion","unquadragintaseptingentillion",
      "Septingentiquadragintabillion or duoquadragintaseptingentillion","tresquadragintaseptingentillion","quattuorquadragintaseptingentillion","quinquaquadragintaseptingentillion",
      "sesquadragintaseptingentillion","septenquadragintaseptingentillion","octoquadragintaseptingentillion","novenquadragintaseptingentillion",
      "quinquagintaseptingentillion","unquinquagintaseptingentillion","duoquinquagintaseptingentillion","tresquinquagintaseptingentillion",
      "quattuorquinquagintaseptingentillion","quinquaquinquagintaseptingentillion","sesquinquagintaseptingentillion","septenquinquagintaseptingentillion",
      "octoquinquagintaseptingentillion","novenquinquagintaseptingentillion","sexagintaseptingentillion","unsexagintaseptingentillion",
      "duosexagintaseptingentillion","tresexagintaseptingentillion","quattuorsexagintaseptingentillion","quinquasexagintaseptingentillion",
      "sesexagintaseptingentillion","septensexagintaseptingentillion","octosexagintaseptingentillion","novensexagintaseptingentillion",
      "septuagintaseptingentillion","unseptuagintaseptingentillion","duoseptuagintaseptingentillion","treseptuagintaseptingentillion",
      "quattuorseptuagintaseptingentillion","quinquaseptuagintaseptingentillion","seseptuagintaseptingentillion","septenseptuagintaseptingentillion",
      "octoseptuagintaseptingentillion","novenseptuagintaseptingentillion","octogintaseptingentillion","unoctogintaseptingentillion",
      "duooctogintaseptingentillion","tresoctogintaseptingentillion","quattuoroctogintaseptingentillion","quinquaoctogintaseptingentillion",
      "sexoctogintaseptingentillion","septemoctogintaseptingentillion","octooctogintaseptingentillion","novemoctogintaseptingentillion",
      "nonagintaseptingentillion","unnonagintaseptingentillion","duononagintaseptingentillion","trenonagintaseptingentillion",
      "quattuornonagintaseptingentillion","quinquanonagintaseptingentillion","senonagintaseptingentillion","septenonagintaseptingentillion",
      "octononagintaseptingentillion","novenonagintaseptingentillion","Octingentillion","unoctingentillion",
      "duooctingentillion","tresoctingentillion","quattuoroctingentillion","quinquaoctingentillion",
      "Sexoctingentillion","septemoctingentillion","octooctingentillion","novemoctingentillion",
      "decioctingentillion","undecioctingentillion","duodecioctingentillion","tredecioctingentillion",
      "quattuordecioctingentillion","quinquadecioctingentillions","sedecioctingentillion","septendecioctingentillion",
      "octodecioctingentillion","novendecioctingentillion","vigintioctingentillion","unvigintioctingentillion",
      "duovigintioctingentillion","tresvigintioctingentillion","quattuorvigintioctingentillion","quinquavigintioctingentillion",
      "sesvigintioctingentillion","septemvigintioctingentillion","octovigintioctingentillion","novemvigintioctingentillion",
      "trigintaoctingentillion","untrigintaoctingentillion","duotrigintaoctingentillion","trestrigintaoctingentillion",
      "quattuortrigintaoctingentillion","quinquatrigintaoctingentillion","sestrigintaoctingentillion","septentrigintaoctingentillion",
      "octotrigintaoctingentillion","noventrigintaoctingentillion","quadragintaoctingentillion","unquadragintaoctingentillion",
      "duoquadragintaoctingentillion","tresquadragintaoctingentillion","quattuorquadragintaoctingentillion","quinquaquadragintaoctingentillion",
      "sesquadragintaoctingentillion","septenquadragintaoctingentillion","octoquadragintaoctingentillion","novenquadragintaoctingentillion",
      "quinquagintaoctingentillion","unquinquagintaoctingentillion","duoquinquagintaoctingentillion","tresquinquagintaoctingentillion",
      "quattuorquinquagintaoctingentillion","quinquaquinquagintaoctingentillion","sesquinquagintaoctingentillion","septenquinquagintaoctingentillion",
      "octoquinquagintaoctingentillion","novenquinquagintaoctingentillion","sexagintaoctingentillion","unsexagintaoctingentillion",
      "duosexagintaoctingentillion","tresexagintaoctingentillion","quattuorsexagintaoctingentillion","quinquasexagintaoctingentillion",
      "sesexagintaoctingentillion","septensexagintaoctingentillion","octosexagintaoctingentillion","novensexagintaoctingentillion",
      "septuagintaoctingentillion","unseptuagintaoctingentillion","duoseptuagintaoctingentillion","treseptuagintaoctingentillion",
      "quattuorseptuagintaoctingentillion","quinquaseptuagintaoctingentillion","seseptuagintaoctingentillion","septenseptuagintaoctingentillion",
      "octoseptuagintaoctingentillion","novenseptuagintaoctingentillion","octogintaoctingentillion","unoctogintaoctingentillion",
      "duooctogintaoctingentillion","tresoctogintaoctingentillion","quattuoroctogintaoctingentillion","quinquaoctogintaoctingentillion",
      "sexoctogintaoctingentillion","septemoctogintaoctingentillion","octooctogintaoctingentillion","novemoctogintaoctingentillion",
      "nonagintaoctingentillion","unnonagintaoctingentillion","duononagintaoctingentillion","trenonagintaoctingentillion",
      "quattuornonagintaoctingentillion","quinquanonagintaoctingentillion","senonagintaoctingentillion","septenonagintaoctingentillion",
      "octononagintaoctingentillion","novenonagintaoctingentillion","Nongentillion","unnongentillion",
      "duonongentillion","trenongentillion","quattuornongentillion","quinquanongentillion",
      "senongentillion","septenongentillion","octonongentillion","novenongentillion",
      "decinongentillion","undecinongentillion","duodecinongentillion","tredecinongentillion",
      "quattuordecinongentillion","quinquadecinongentillion","sedecinongentillion","septendecinongentillion",
      "octodecinongentillion","novendecinongentillion","vigintinongentillion","unvigintinongentillion",
      "duovigintinongentillion","tresvigintinongentillion","quattuorvigintinongentillion","quinquavigintinongentillion",
      "sesvigintinongentillion","septemvigintinongentillion","octovigintinongentillion","novemvigintinongentillion",
      "trigintanongentillion","untrigintanongentillion","duotrigintanongentillion","trestrigintanongentillion",
      "quattuortrigintanongentillion","quinquatrigintanongentillion","sestrigintanongentillion","septentrigintanongentillion",
      "octotrigintanongentillion","noventrigintanongentillion","quadragintanongentillion","unquadragintanongentillion",
      "duoquadragintanongentillion","tresquadragintanongentillion","quattuorquadragintanongentillion","quinquaquadragintanongentillion",
      "sesquadragintanongentillion","septenquadragintanongentillion","octoquadragintanongentillion","novenquadragintanongentillion",
      "quinquagintanongentillion","unquinquagintanongentillion","duoquinquagintanongentillion","tresquinquagintanongentillion",
      "quattuorquinquagintanongentillion","quinquaquinquagintanongentillion","sesquinquagintanongentillion","septenquinquagintanongentillion",
      "octoquinquagintanongentillion","novenquinquagintanongentillion","sexagintanongentillion","unsexagintanongentillion",
      "duosexagintanongentillion","tresexagintanongentillion","quattuorsexagintanongentillion","quinquasexagintanongentillion",
      "sesexagintanongentillion","septensexagintanongentillion","octosexagintanongentillion","novensexagintanongentillion",
      "septuagintanongentillion","unseptuagintanongentillion","duoseptuagintanongentillion","treseptuagintanongentillion",
      "quattuorseptuagintanongentillion","quinquaseptuagintanongentillion","seseptuagintanongentillion","septenseptuagintanongentillion",
      "octoseptuagintanongentillion","novenseptuagintanongentillion","octogintanongentillion","unoctogintanongentillion",
      "duooctogintanongentillion","tresoctogintanongentillion","quattuoroctogintanongentillion","quinquaoctogintanongentillion",
      "sexoctogintanongentillion","septemoctogintanongentillion","octooctogintanongentillion","novemoctogintanongentillion",
      "nonagintanongentillion","unnonagintanongentillion","duononagintanongentillion","Trenonagintanongentillion",
      "quattuornonagintanongentillion","quinquanonagintanongentillion","Senonagintanongentillion","septenonagintanongentillion",
      "octononagintanongentillion","nongentinonagentanonillion or undemillillion or googood or","novenonagintanongentillion","Millillion"};
  int s = 0;
  int i = (l % 3 == 0) ? 3:(l % 3);
  if(i > l) i = l;
  while(i <= l) {
    char cnum[4]={0};
    strncpy(cnum, &numbuf[s], &numbuf[i] - &numbuf[s]);
    int n = atoi(cnum);
    n2w(n);
    if(n > 0) printf(" %s ", lions[(l - i)/3]);
    s = i;
    i += 3;
  }
  printf("\n");
  return 0;
}

